run:
  timeout: 2m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
    - gocritic
    - gosec
    - prealloc

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
